window.liff.init(
  data => {
    const {userId} = data.context
    const accessToken = window.liff.getAccessToken()
    console.log(userId, accessToken)
  },
  error => {
    console.error(error)
  },
)

export default () => {
  console.log('generated by liff-app-template')
  const root = window.document.getElementById('root')
  if (root) {
    root.innerText = 'generated by liff-app-template'
  }
}
