import liff from '@line/liff'

import init from './init'

export default async () => {
  const liffId = process.env.LIFF_ID
  if (liffId === undefined) {
    throw new Error('this is unreached')
  }

  const root = window.document.getElementById('root')
  if (root === null) {
    throw new Error('this is unreached')
  }

  try {
    await init()

    const profile = await liff.getProfile()
    root.innerHTML = `
      <div>generated by liff-app-template</div>
      <div>${profile.displayName}</div>
      <img src=${profile.pictureUrl}>
    `
  }
  catch(error) {
    root.innerHTML = `<pre>${error}</pre>`
  }
}
